# Generated by GPT-4 with minor modifications
# Wraps C-API funciton calls with CALL_C_API_FUNC macro

import os
import re


def process_file(file_path, new_file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()

    include_section_end = 0
    for index, line in enumerate(lines):
        if line.startswith('#include'):
            include_section_end = index

    macro_def = '''
#include "AOTPlugin.h"

/*
  This is a modified version of the original "taichi/cpp/taichi.hpp"
  Since UE5 loads third-party libraries in "dlopen" manner, we need to
  use "dlsym" to get the address of the function we want to call.

  All direct function calls to C-API in the original taichi.hpp are
  replaced by the CALL_C_API_FUNC macro.
*/

#define CALL_C_API_FUNC(FunctionName)                                                                                                                            \\
[]() {                                                                                                                                                     \\
	using FunctionType = decltype(&FunctionName);                                                                                                          \\
	const FAOTPluginModule& CurrentModule = FModuleManager::GetModuleChecked<FAOTPluginModule>(TEXT("AOTPlugin"));                                      \\
	static FunctionType FunctionPtr = (FunctionType)(FPlatformProcess::GetDllExport(CurrentModule.LibraryHandle, TEXT(#FunctionName)));          \\
	return FunctionPtr;                                                                                                                                    \\
}()
'''
    lines.insert(include_section_end + 1, macro_def)

    ti_pattern = re.compile(r'(ti_[a-zA-Z0-9_]+)\s*\(')

    processed_lines = []
    for line in lines:
        line = ti_pattern.sub(r'CALL_C_API_FUNC(\1)(', line)
        processed_lines.append(line)

    with open(new_file_path, 'w') as f:
        f.writelines(processed_lines)


if __name__ == "__main__":
    file_path = 'c_api/include/taichi/cpp/taichi.hpp'
    new_file_path = 'c_api/include/taichi/cpp/taichi_unreal.hpp'
    process_file(file_path, new_file_path)
