ci:
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: '[misc] Update pre-commit hooks'

default_language_version:
    python: python3.10

exclude: ^((tests/python/test_exception)\.py$|external/)
repos:
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        exclude: .*\.json$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.9
    hooks:
      - id: pylint
        args: ['-rn', '-sn']
        files: ^python/taichi/
