// Potentially supported OpenGL extensions

PER_OPENGL_EXTENSION(GL_ARB_compute_shader)
PER_OPENGL_EXTENSION(GL_ARB_gpu_shader_int64)
PER_OPENGL_EXTENSION(GL_NV_shader_atomic_float)
PER_OPENGL_EXTENSION(GL_NV_shader_atomic_float64)
PER_OPENGL_EXTENSION(GL_NV_shader_atomic_int64)
