# How to update the env:
#
# conda activate taichi-dev
# conda env update --file conda-env.yaml --prune
# https://stackoverflow.com/a/43873901/12003165

name: taichi-dev
dependencies:
  - python=3.8  # Replace this with your favorite Python version
