#pragma once

#define ASYNC_ENGINE_RELEASE_MODE

#ifdef ASYNC_ENGINE_RELEASE_MODE
#undef TI_PROFILER
#undef TI_AUTO_PROF

#define TI_PROFILER(name)
#define TI_AUTO_PROF
#endif  // ASYNC_ENGINE_RELEASE_MODE
