"""Key constants for :mod:`~taichi.ui`"""

SHIFT = "Shift"
ALT = "Alt"
CTRL = "Control"
ESCAPE = "Escape"
RETURN = "Return"
TAB = "Tab"
BACKSPACE = "BackSpace"
SPACE = " "
UP = "Up"
DOWN = "Down"
LEFT = "Left"
RIGHT = "Right"
CAPSLOCK = "CapsLock"
LMB = "LMB"
MMB = "MMB"
RMB = "RMB"

# Function keys
F1 = "F1"
F2 = "F2"
F3 = "F3"
F4 = "F4"
F5 = "F5"
F6 = "F6"
F7 = "F7"
F8 = "F8"
F9 = "F9"
F10 = "F10"
F11 = "F11"
F12 = "F12"

# Navigation keys
INSERT = "Insert"
DELETE = "Delete"
HOME = "Home"
END = "End"
PAGEUP = "PageUp"
PAGEDOWN = "PageDown"

# Numpad keys
NUMPAD0 = "Numpad0"
NUMPAD1 = "Numpad1"
NUMPAD2 = "Numpad2"
NUMPAD3 = "Numpad3"
NUMPAD4 = "Numpad4"
NUMPAD5 = "Numpad5"
NUMPAD6 = "Numpad6"
NUMPAD7 = "Numpad7"
NUMPAD8 = "Numpad8"
NUMPAD9 = "Numpad9"
NUMPAD_DECIMAL = "NumpadDecimal"
NUMPAD_DIVIDE = "NumpadDivide"
NUMPAD_MULTIPLY = "NumpadMultiply"
NUMPAD_SUBTRACT = "NumpadSubtract"
NUMPAD_ADD = "NumpadAdd"
NUMPAD_ENTER = "NumpadEnter"

# Event types
PRESS = "Press"
RELEASE = "Release"
