SHIFT = 'Shift'
ALT = 'Alt'
CTRL = 'Control'
ESCAPE = 'Escape'
RETURN = 'Return'
TAB = 'Tab'
BACKSPACE = 'BackSpace'
SPACE = 'Space'
UP = 'Up'
DOWN = 'Down'
LEFT = 'Left'
RIGHT = 'Right'
CAPSLOCK = 'CapsLock'
LMB = 'LMB'
MMB = 'MMB'
RMB = 'RMB'

# Event types
PRESS = "Press"
RELEASE = "Release"
