# CMakeGraphVizOptions.cmake
set(GRAPHVIZ_EXTERNAL_LIBS FALSE)
set(GRAPHVIZ_INTERFACE_LIBS FALSE)
set(GRAPHVIZ_EXECUTABLES FALSE)
set(GRAPHVIZ_GENERATE_PER_TARGET FALSE)
set(GRAPHVIZ_GENERATE_DEPENDERS FALSE)
set(GRAPHVIZ_GENERATE_DEPENDERS FALSE)
set(GRAPHVIZ_IGNORE_TARGETS "SPIRV-Tools*;spirv-cross*;gtest*;gmock*")
