name: "Taichi Daily Check"
on:
  schedule:
  - cron: "0 0 * * *"  # run on 00:00 of every day

jobs:
  stale_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'Warning: The PR has been out-of-update for 12 days, marking `stale`.'
        stale-pr-label: 'stale'
        days-before-stale: 12
        days-before-close: -1
  stale_issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Warning: The issue has been out-of-update for 50 days, marking `stale`.'
        stale-issue-label: 'stale'
        days-before-stale: 50
        days-before-close: -1
